### ISSUE TITLE
Problems creating a second WordPress install with a shared database

### ISSUE THREAD

**Issue by avidsapp** [evertramos/docker-wordpress-letsencrypt#36]
I have successfully set up separate WordPress installs without changing the service names in the docker-compose.yml as referenced by #24, but rather installing in subdomains with different container names for WP and the db and housing the sites in separate directories. This spins up separate db containers. Now I want to be able to share an already running database container, but create a new WP container. How can I accomplish this?

```
version: '3'
services:
   db:
     container_name: ${CONTAINER_DB_NAME}
     image: mariadb:latest
     restart: unless-stopped
     volumes:
        - ${DB_PATH}:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
     external_links:
        - sitename-db
...
```

with .env showing:

```
...

# Path to store your database
#DB_PATH=/path/to/your/local/database/folder
DB_PATH=../sitename/data

...
```

outputs

```
ERROR: for sitename-db  Cannot create container for service db: Conflict. The container name "/sitename-db" is already in use by container "13rjbwdv98wdvb2...". You have to remove (or rename) that container to be able to reuse that name.
```

After connecting to a shared database, I can edit the WP install itself.
